#! /usr/bin/env python

import Options
import Utils
import Build

VERSION = '0.1.0'
APPNAME = 'thunar-meocloud'

top = '.'
out = 'build'

def set_options(opt):
	opt.tool_options('compiler_cc')
	opt.tool_options('gnu_dirs')

def configure(conf):
	conf.check_tool('compiler_cc')
	conf.check_cfg(package='thunarx-2', uselib_store='THUNARX', mandatory=True, args='--cflags --libs')
	conf.check_cfg(package='gio-2.0', uselib_store='GIO', mandatory=True, args='--cflags --libs')

def build(bld):
	prog = bld.new_task_gen('cc', 'cshlib')
	prog.target = 'thunar-meocloud'
	prog.install_path = None
	prog.uselib = 'THUNARX THUNARVFS'
	prog.includes = 'src'
	prog.find_sources_in_dirs('src')
	bld.install_as('${PREFIX}/lib/thunarx-2/thunar-meocloud.so', 'libthunar-meocloud.so')

def shutdown():
	pass
