/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp pt.meocloud.shell.xml -a ShellBus
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dolphin-meocloud-dbus.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ShellAdaptor
 */

ShellAdaptor::ShellAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ShellAdaptor::~ShellAdaptor()
{
    // destructor
}

void ShellAdaptor::UpdateFile(const QString &path)
{
    // handle method call pt.meocloud.shell.UpdateFile
    QMetaObject::invokeMethod(parent(), "UpdateFile", Q_ARG(QString, path));
}
