/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef shell_CONSTANTS_H
#define shell_CONSTANTS_H

#include "shell_types.h"

namespace Shell {

class shellConstants {
 public:
  shellConstants();

};

extern const shellConstants g_shell_constants;

} // namespace

#endif
