/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "shell_constants.h"

namespace Shell {

const shellConstants g_shell_constants;

shellConstants::shellConstants() {
}

} // namespace

