/* plugin.c generated by valac 0.22.1, the Vala compiler
 * generated from plugin.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <marlincore.h>
#include <gtk/gtk.h>
#include <gof-file.h>
#include <gio/gio.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define MARLIN_PLUGINS_TYPE_MEO_CLOUD (marlin_plugins_meo_cloud_get_type ())
#define MARLIN_PLUGINS_MEO_CLOUD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MARLIN_PLUGINS_TYPE_MEO_CLOUD, MarlinPluginsMEOCloud))
#define MARLIN_PLUGINS_MEO_CLOUD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MARLIN_PLUGINS_TYPE_MEO_CLOUD, MarlinPluginsMEOCloudClass))
#define MARLIN_PLUGINS_IS_MEO_CLOUD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MARLIN_PLUGINS_TYPE_MEO_CLOUD))
#define MARLIN_PLUGINS_IS_MEO_CLOUD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MARLIN_PLUGINS_TYPE_MEO_CLOUD))
#define MARLIN_PLUGINS_MEO_CLOUD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MARLIN_PLUGINS_TYPE_MEO_CLOUD, MarlinPluginsMEOCloudClass))

typedef struct _MarlinPluginsMEOCloud MarlinPluginsMEOCloud;
typedef struct _MarlinPluginsMEOCloudClass MarlinPluginsMEOCloudClass;
typedef struct _MarlinPluginsMEOCloudPrivate MarlinPluginsMEOCloudPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _MarlinPluginsMEOCloud {
	MarlinPluginsBase parent_instance;
	MarlinPluginsMEOCloudPrivate * priv;
};

struct _MarlinPluginsMEOCloudClass {
	MarlinPluginsBaseClass parent_class;
};

struct _MarlinPluginsMEOCloudPrivate {
	GtkUIManager* ui_manager;
	GtkMenu* menu;
	GOFFile* current_directory;
};


static gpointer marlin_plugins_meo_cloud_parent_class = NULL;

GType marlin_plugins_meo_cloud_get_type (void) G_GNUC_CONST;
#define MARLIN_PLUGINS_MEO_CLOUD_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MARLIN_PLUGINS_TYPE_MEO_CLOUD, MarlinPluginsMEOCloudPrivate))
enum  {
	MARLIN_PLUGINS_MEO_CLOUD_DUMMY_PROPERTY
};
MarlinPluginsMEOCloud* marlin_plugins_meo_cloud_new (void);
MarlinPluginsMEOCloud* marlin_plugins_meo_cloud_construct (GType object_type);
static void marlin_plugins_meo_cloud_real_context_menu (MarlinPluginsBase* base, GtkWidget* widget, GList* gof_files);
static void marlin_plugins_meo_cloud_add_menuitem (MarlinPluginsMEOCloud* self, GtkMenu* menu, GtkMenuItem* menu_item);
static void marlin_plugins_meo_cloud_real_ui (MarlinPluginsBase* base, GtkUIManager* widget);
static void marlin_plugins_meo_cloud_real_directory_loaded (MarlinPluginsBase* base, void* user_data);
static gchar** marlin_plugins_meo_cloud_get_mimetypes (GList* files, int* result_length1);
static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value);
static GFile** marlin_plugins_meo_cloud_get_file_array (GList* files, int* result_length1);
static void _vala_array_add2 (GFile*** array, int* length, int* size, GFile* value);
static void marlin_plugins_meo_cloud_finalize (MarlinPluginsBase* obj);
MarlinPluginsBase* module_init (void);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


MarlinPluginsMEOCloud* marlin_plugins_meo_cloud_construct (GType object_type) {
	MarlinPluginsMEOCloud* self = NULL;
	self = (MarlinPluginsMEOCloud*) marlin_plugins_base_construct (object_type);
	return self;
}


MarlinPluginsMEOCloud* marlin_plugins_meo_cloud_new (void) {
	return marlin_plugins_meo_cloud_construct (MARLIN_PLUGINS_TYPE_MEO_CLOUD);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void marlin_plugins_meo_cloud_real_context_menu (MarlinPluginsBase* base, GtkWidget* widget, GList* gof_files) {
	MarlinPluginsMEOCloud * self;
	GtkWidget* _tmp0_ = NULL;
	GtkMenu* _tmp1_ = NULL;
	GtkMenu* _tmp2_ = NULL;
	GFile** files = NULL;
	gint files_length1 = 0;
	gint _files_size_ = 0;
	GtkMenuItem* menu_item = NULL;
	GtkMenuItem* _tmp3_ = NULL;
	GtkMenu* _tmp4_ = NULL;
	self = (MarlinPluginsMEOCloud*) base;
	_tmp0_ = widget;
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, GTK_TYPE_MENU) ? ((GtkMenu*) _tmp0_) : NULL);
	_g_object_unref0 (self->priv->menu);
	self->priv->menu = _tmp1_;
	_tmp2_ = self->priv->menu;
	g_return_if_fail (_tmp2_ != NULL);
	files = NULL;
	files_length1 = 0;
	_files_size_ = files_length1;
	_tmp3_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("test");
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (menu_item);
	menu_item = _tmp3_;
	_tmp4_ = self->priv->menu;
	marlin_plugins_meo_cloud_add_menuitem (self, _tmp4_, menu_item);
	_g_object_unref0 (menu_item);
	files = (_vala_array_free (files, files_length1, (GDestroyNotify) g_object_unref), NULL);
}


static void marlin_plugins_meo_cloud_real_ui (MarlinPluginsBase* base, GtkUIManager* widget) {
	MarlinPluginsMEOCloud * self;
	GtkUIManager* _tmp0_ = NULL;
	GtkUIManager* _tmp1_ = NULL;
	GtkUIManager* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	GtkMenu* _tmp4_ = NULL;
	self = (MarlinPluginsMEOCloud*) base;
	_tmp0_ = widget;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->ui_manager);
	self->priv->ui_manager = _tmp1_;
	_tmp2_ = self->priv->ui_manager;
	_tmp3_ = gtk_ui_manager_get_widget (_tmp2_, "/selection");
	_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, GTK_TYPE_MENU, GtkMenu));
	_g_object_unref0 (self->priv->menu);
	self->priv->menu = _tmp4_;
}


static void marlin_plugins_meo_cloud_real_directory_loaded (MarlinPluginsBase* base, void* user_data) {
	MarlinPluginsMEOCloud * self;
	void* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GOFFile* _tmp2_ = NULL;
	self = (MarlinPluginsMEOCloud*) base;
	_tmp0_ = user_data;
	_tmp1_ = ((GObject**) _tmp0_)[2];
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GOF_TYPE_FILE) ? ((GOFFile*) _tmp1_) : NULL);
	_g_object_unref0 (self->priv->current_directory);
	self->priv->current_directory = _tmp2_;
}


static void marlin_plugins_meo_cloud_add_menuitem (MarlinPluginsMEOCloud* self, GtkMenu* menu, GtkMenuItem* menu_item) {
	GtkMenu* _tmp0_ = NULL;
	GtkMenuItem* _tmp1_ = NULL;
	GtkMenuItem* _tmp2_ = NULL;
	MarlinPluginManager* _tmp3_ = NULL;
	GeeList* _tmp4_ = NULL;
	GeeList* _tmp5_ = NULL;
	GtkMenuItem* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (menu != NULL);
	g_return_if_fail (menu_item != NULL);
	_tmp0_ = menu;
	_tmp1_ = menu_item;
	gtk_menu_shell_append ((GtkMenuShell*) _tmp0_, (GtkWidget*) _tmp1_);
	_tmp2_ = menu_item;
	gtk_widget_show ((GtkWidget*) _tmp2_);
	_tmp3_ = plugins;
	_tmp4_ = marlin_plugin_manager_get_menuitem_references (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = menu_item;
	gee_collection_add ((GeeCollection*) _tmp5_, (GtkWidget*) _tmp6_);
}


static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static gchar** marlin_plugins_meo_cloud_get_mimetypes (GList* files, int* result_length1) {
	gchar** result = NULL;
	gchar** mimetypes = NULL;
	gchar** _tmp0_ = NULL;
	gint mimetypes_length1 = 0;
	gint _mimetypes_size_ = 0;
	GList* _tmp1_ = NULL;
	gchar** _tmp10_ = NULL;
	gint _tmp10__length1 = 0;
	_tmp0_ = g_new0 (gchar*, 0 + 1);
	mimetypes = _tmp0_;
	mimetypes_length1 = 0;
	_mimetypes_size_ = mimetypes_length1;
	_tmp1_ = files;
	{
		GList* file_collection = NULL;
		GList* file_it = NULL;
		file_collection = _tmp1_;
		for (file_it = file_collection; file_it != NULL; file_it = file_it->next) {
			GOFFile* _tmp2_ = NULL;
			GOFFile* file = NULL;
			_tmp2_ = _g_object_ref0 ((GOFFile*) file_it->data);
			file = _tmp2_;
			{
				gchar* ftype = NULL;
				GOFFile* _tmp3_ = NULL;
				const gchar* _tmp4_ = NULL;
				gchar* _tmp5_ = NULL;
				const gchar* _tmp6_ = NULL;
				_tmp3_ = file;
				_tmp4_ = gof_file_get_ftype (_tmp3_);
				_tmp5_ = g_strdup (_tmp4_);
				ftype = _tmp5_;
				_tmp6_ = ftype;
				if (_tmp6_ != NULL) {
					gchar** _tmp7_ = NULL;
					gint _tmp7__length1 = 0;
					const gchar* _tmp8_ = NULL;
					gchar* _tmp9_ = NULL;
					_tmp7_ = mimetypes;
					_tmp7__length1 = mimetypes_length1;
					_tmp8_ = ftype;
					_tmp9_ = g_strdup (_tmp8_);
					_vala_array_add1 (&mimetypes, &mimetypes_length1, &_mimetypes_size_, _tmp9_);
				}
				_g_free0 (ftype);
				_g_object_unref0 (file);
			}
		}
	}
	_tmp10_ = mimetypes;
	_tmp10__length1 = mimetypes_length1;
	if (result_length1) {
		*result_length1 = _tmp10__length1;
	}
	result = _tmp10_;
	return result;
}


static void _vala_array_add2 (GFile*** array, int* length, int* size, GFile* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GFile*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static GFile** marlin_plugins_meo_cloud_get_file_array (GList* files, int* result_length1) {
	GFile** result = NULL;
	GFile** file_array = NULL;
	GFile** _tmp0_ = NULL;
	gint file_array_length1 = 0;
	gint _file_array_size_ = 0;
	GList* _tmp1_ = NULL;
	GFile** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	_tmp0_ = g_new0 (GFile*, 0 + 1);
	file_array = _tmp0_;
	file_array_length1 = 0;
	_file_array_size_ = file_array_length1;
	_tmp1_ = files;
	{
		GList* file_collection = NULL;
		GList* file_it = NULL;
		file_collection = _tmp1_;
		for (file_it = file_collection; file_it != NULL; file_it = file_it->next) {
			GOFFile* _tmp2_ = NULL;
			GOFFile* file = NULL;
			_tmp2_ = _g_object_ref0 ((GOFFile*) file_it->data);
			file = _tmp2_;
			{
				GOFFile* _tmp3_ = NULL;
				GFile* _tmp4_ = NULL;
				_tmp3_ = file;
				_tmp4_ = _tmp3_->location;
				if (_tmp4_ != NULL) {
					GFile** _tmp5_ = NULL;
					gint _tmp5__length1 = 0;
					GOFFile* _tmp6_ = NULL;
					GFile* _tmp7_ = NULL;
					GFile* _tmp8_ = NULL;
					_tmp5_ = file_array;
					_tmp5__length1 = file_array_length1;
					_tmp6_ = file;
					_tmp7_ = _tmp6_->location;
					_tmp8_ = _g_object_ref0 (_tmp7_);
					_vala_array_add2 (&file_array, &file_array_length1, &_file_array_size_, _tmp8_);
				}
				_g_object_unref0 (file);
			}
		}
	}
	_tmp9_ = file_array;
	_tmp9__length1 = file_array_length1;
	if (result_length1) {
		*result_length1 = _tmp9__length1;
	}
	result = _tmp9_;
	return result;
}


static void marlin_plugins_meo_cloud_class_init (MarlinPluginsMEOCloudClass * klass) {
	marlin_plugins_meo_cloud_parent_class = g_type_class_peek_parent (klass);
	MARLIN_PLUGINS_BASE_CLASS (klass)->finalize = marlin_plugins_meo_cloud_finalize;
	g_type_class_add_private (klass, sizeof (MarlinPluginsMEOCloudPrivate));
	MARLIN_PLUGINS_BASE_CLASS (klass)->context_menu = marlin_plugins_meo_cloud_real_context_menu;
	MARLIN_PLUGINS_BASE_CLASS (klass)->ui = marlin_plugins_meo_cloud_real_ui;
	MARLIN_PLUGINS_BASE_CLASS (klass)->directory_loaded = marlin_plugins_meo_cloud_real_directory_loaded;
}


static void marlin_plugins_meo_cloud_instance_init (MarlinPluginsMEOCloud * self) {
	self->priv = MARLIN_PLUGINS_MEO_CLOUD_GET_PRIVATE (self);
	self->priv->current_directory = NULL;
}


static void marlin_plugins_meo_cloud_finalize (MarlinPluginsBase* obj) {
	MarlinPluginsMEOCloud * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MARLIN_PLUGINS_TYPE_MEO_CLOUD, MarlinPluginsMEOCloud);
	_g_object_unref0 (self->priv->ui_manager);
	_g_object_unref0 (self->priv->menu);
	_g_object_unref0 (self->priv->current_directory);
	MARLIN_PLUGINS_BASE_CLASS (marlin_plugins_meo_cloud_parent_class)->finalize (obj);
}


GType marlin_plugins_meo_cloud_get_type (void) {
	static volatile gsize marlin_plugins_meo_cloud_type_id__volatile = 0;
	if (g_once_init_enter (&marlin_plugins_meo_cloud_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MarlinPluginsMEOCloudClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) marlin_plugins_meo_cloud_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MarlinPluginsMEOCloud), 0, (GInstanceInitFunc) marlin_plugins_meo_cloud_instance_init, NULL };
		GType marlin_plugins_meo_cloud_type_id;
		marlin_plugins_meo_cloud_type_id = g_type_register_static (MARLIN_PLUGINS_TYPE_BASE, "MarlinPluginsMEOCloud", &g_define_type_info, 0);
		g_once_init_leave (&marlin_plugins_meo_cloud_type_id__volatile, marlin_plugins_meo_cloud_type_id);
	}
	return marlin_plugins_meo_cloud_type_id__volatile;
}


MarlinPluginsBase* module_init (void) {
	MarlinPluginsBase* result = NULL;
	MarlinPluginsMEOCloud* _tmp0_ = NULL;
	_tmp0_ = marlin_plugins_meo_cloud_new ();
	result = (MarlinPluginsBase*) _tmp0_;
	return result;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



